Task 006/upgrade c make lists (issue #6)
GRPilot/lazycoder pull request #7
Opened 2021-08-10 06:10 UTC by GRPilot

I also add some comments in CMakeLists and *.cmake files as asked [here](https://github.com/GRPilot/lazycoder/projects/1#card-66461140)

Now you can forget about changing something in CMakeLists because CMake collects all your new files and directories themselves.

2021-08-10 08:32 UTC, seigtm requested changes
Check CMakeLists. I left commentary there

2021-08-10 08:32 UTC, seigtm commented on CMakeLists.txt
> +cmake_minimum_required(VERSION 3.5) # The smallest abailable cmake version for use
available

2021-08-10 11:27 UTC, seigtm commented on CMakeLists.txt
> +cmake_minimum_required(VERSION 3.5) # The smallest abailable cmake version for use
"to use"

2021-08-10 13:51 UTC, GRPilot commented on CMakeLists.txt
> +cmake_minimum_required(VERSION 3.5) # The smallest abailable cmake version for use
fixed in commit 08f5be3

2021-08-11 07:35 UTC, seigtm approved these changes

2021-08-11 07:44 UTC, closed without merging